variables:
  BUILD_DEPS: libamxc libamxj libamxp libamxd libamxo libamxb libevent-dev libcap-ng-dev

include:
  - remote: 'https://gitlab.com/soft.at.home/ci/gitlab-ci/raw/main/ambiorix-default-pipeline.yml'
